package net.x666c.simplereddit.bot;

public class SubredditsFiltered {
	
	public static final String SUBREDDITS = 
			
			"gifs\r\n" + 
			"behindthegifs\r\n" + 
			"gif\r\n" + 
			"Cinemagraphs\r\n" + 
			"WastedGifs\r\n" + 
			"educationalgifs\r\n" + 
			"perfectloops\r\n" + 
			"highqualitygifs\r\n" + 
			"gifsound\r\n" + 
			"combinedgifs\r\n" + 
			"retiredgif\r\n" + 
			"michaelbaygifs\r\n" + 
			"gifrecipes\r\n" + 
			"mechanical_gifs\r\n" + 
			"bettereveryloop\r\n" + 
			"gifextra\r\n" + 
			"slygifs\r\n" + 
			"gifsthatkeepongiving\r\n" + 
			"wholesomegifs\r\n" + 
			"noisygifs\r\n" + 
			"brokengifs\r\n" + 
			"loadingicon\r\n" + 
			"splitdepthgifs\r\n" + 
			"blackpeoplegifs\r\n" + 
			"whitepeoplegifs\r\n" + 
			"asianpeoplegifs\r\n" + 
			"scriptedasiangifs\r\n" + 
			"reactiongifs\r\n" + 
			"shittyreactiongifs\r\n" + 
			"chemicalreactiongifs\r\n" + 
			"physicsgifs\r\n" + 
			"babyelephantgifs\r\n" + 
			"weathergifs\r\n" + 
			"pics\r\n" + 
			"PhotoshopBattles\r\n" + 
			"perfecttiming\r\n" + 
			"itookapicture\r\n" + 
			"Pareidolia\r\n" + 
			"ExpectationVSReality\r\n" + 
			"dogpictures\r\n" + 
			"misleadingthumbnails\r\n" + 
			"FifthWorldPics\r\n" + 
			"TheWayWeWere\r\n" + 
			"pic\r\n" + 
			"nocontextpics\r\n" + 
			"miniworlds\r\n" + 
			"foundpaper\r\n" + 
			"images\r\n" + 
			"screenshots\r\n" + 
			"mildlyinteresting\r\n" + 
			"interestingasfuck\r\n" + 
			"damnthatsinteresting\r\n" + 
			"beamazed\r\n" + 
			"reallifeshinies\r\n" + 
			"thatsinsane\r\n" + 
			"playitagainsam\r\n" + 
			"gentlemanboners\r\n" + 
			"prettygirls\r\n" + 
			"hardbodies\r\n" + 
			"girlsmirin\r\n" + 
			"thinspo\r\n" + 
			"goddesses\r\n" + 
			"shorthairedhotties\r\n" + 
			"fitandnatural\r\n" + 
			"wrestlewiththeplot\r\n" + 
			"skinnywithabs\r\n" + 
			"bois\r\n" + 
			"GentlemanBonersGifs\r\n" + 
			"asiancuties\r\n" + 
			"asiangirlsbeingcute\r\n" + 
			"PhotoshopBattles\r\n" + 
			"ColorizedHistory\r\n" + 
			"reallifedoodles\r\n" + 
			"HybridAnimals\r\n" + 
			"colorization\r\n" + 
			"amiugly\r\n" + 
			"roastme\r\n" + 
			"rateme\r\n" + 
			"uglyduckling\r\n" + 
			"prettygirlsuglyfaces\r\n" + 
			"wallpapers\r\n" + 
			"wallpaper\r\n" + 
			"Offensive_Wallpapers\r\n" + 
			"videos\r\n" + 
			"youtubehaiku\r\n" + 
			"artisanvideos\r\n" + 
			"DeepIntoYouTube\r\n" + 
			"nottimanderic\r\n" + 
			"praisethecameraman\r\n" + 
			"killthecameraman\r\n" + 
			"perfectlycutscreams\r\n" + 
			"donthelpjustfilm\r\n" + 
			"abruptchaos\r\n" + 
			"ShowerThoughts\r\n" + 
			"DoesAnybodyElse\r\n" + 
			"changemyview\r\n" + 
			"crazyideas\r\n" + 
			"howtonotgiveafuck\r\n" + 
			"tipofmytongue\r\n" + 
			"quotes\r\n" + 
			"casualconversation\r\n" + 
			"makenewfriendshere\r\n" + 
			"relationship_advice\r\n" + 
			"raisedbynarcissists\r\n" + 
			"legaladvice\r\n" + 
			"advice\r\n" + 
			"amitheasshole\r\n" + 
			"mechanicadvice\r\n" + 
			"toastme\r\n" + 
			"needadvice\r\n" + 
			"IAmA\r\n" + 
			"ExplainlikeIAmA\r\n" + 
			"AMA\r\n" + 
			"casualiama\r\n" + 
			"de_Iama\r\n" + 
			"whowouldwin\r\n" + 
			"wouldyourather\r\n" + 
			"scenesfromahat\r\n" + 
			"AskOuija\r\n" + 
			"themonkeyspaw\r\n" + 
			"shittysuperpowers\r\n" + 
			"godtiersuperpowers\r\n" + 
			"decreasinglyverbose\r\n" + 
			"jesuschristouija\r\n" + 
			"whatisthisthing\r\n" + 
			"answers\r\n" + 
			"NoStupidQuestions\r\n" + 
			"amiugly\r\n" + 
			"whatsthisbug\r\n" + 
			"samplesize\r\n" + 
			"tooafraidtoask\r\n" + 
			"whatsthisplant\r\n" + 
			"isitbullshit\r\n" + 
			"morbidquestions\r\n" + 
			"AskReddit\r\n" + 
			"ShittyAskScience\r\n" + 
			"TrueAskReddit\r\n" + 
			"AskScienceFiction\r\n" + 
			"AskOuija\r\n" + 
			"AskScience\r\n" + 
			"askhistorians\r\n" + 
			"askculinary\r\n" + 
			"AskSocialScience\r\n" + 
			"askengineers\r\n" + 
			"askphilosophy\r\n" + 
			"askdocs\r\n" + 
			"askwomen\r\n" + 
			"askmen\r\n" + 
			"askgaybros\r\n" + 
			"askredditafterdark\r\n" + 
			"asktransgender\r\n" + 
			"askmenover30\r\n" + 
			"tifu\r\n" + 
			"self\r\n" + 
			"confession\r\n" + 
			"fatpeoplestories\r\n" + 
			"confessions\r\n" + 
			"storiesaboutkevin\r\n" + 
			"talesfromtechsupport\r\n" + 
			"talesfromretail\r\n" + 
			"techsupportmacgyver\r\n" + 
			"idontworkherelady\r\n" + 
			"TalesFromYourServer\r\n" + 
			"KitchenConfidential\r\n" + 
			"TalesFromThePizzaGuy\r\n" + 
			"TalesFromTheFrontDesk\r\n" + 
			"talesfromthecustomer\r\n" + 
			"talesfromcallcenters\r\n" + 
			"talesfromthesquadcar\r\n" + 
			"talesfromthepharmacy\r\n" + 
			"starbucks\r\n" + 
			"pettyrevenge\r\n" + 
			"prorevenge\r\n" + 
			"nuclearrevenge\r\n" + 
			"nosleep\r\n" + 
			"LetsNotMeet\r\n" + 
			"Glitch_in_the_Matrix\r\n" + 
			"shortscarystories\r\n" + 
			"thetruthishere\r\n" + 
			"UnresolvedMysteries\r\n" + 
			"UnsolvedMysteries\r\n" + 
			"depression\r\n" + 
			"SuicideWatch\r\n" + 
			"Anxiety\r\n" + 
			"foreveralone\r\n" + 
			"offmychest\r\n" + 
			"socialanxiety\r\n" + 
			"trueoffmychest\r\n" + 
			"unsentletters\r\n" + 
			"rant\r\n" + 
			"YouShouldKnow\r\n" + 
			"everymanshouldknow\r\n" + 
			"LearnUselessTalents\r\n" + 
			"changemyview\r\n" + 
			"howto\r\n" + 
			"Foodforthought\r\n" + 
			"educationalgifs\r\n" + 
			"lectures\r\n" + 
			"education\r\n" + 
			"college\r\n" + 
			"GetStudying\r\n" + 
			"teachers\r\n" + 
			"watchandlearn\r\n" + 
			"bulletjournal\r\n" + 
			"applyingtocollege\r\n" + 
			"lawschool\r\n" + 
			"todayilearned\r\n" + 
			"wikipedia\r\n" + 
			"OutOfTheLoop\r\n" + 
			"IWantToLearn\r\n" + 
			"explainlikeimfive\r\n" + 
			"explainlikeIAmA\r\n" + 
			"ExplainLikeImCalvin\r\n" + 
			"anthropology\r\n" + 
			"Art\r\n" + 
			"redditgetsdrawn\r\n" + 
			"heavymind\r\n" + 
			"drawing\r\n" + 
			"graffiti\r\n" + 
			"retrofuturism\r\n" + 
			"sketchdaily\r\n" + 
			"ArtPorn\r\n" + 
			"pixelart\r\n" + 
			"artfundamentals\r\n" + 
			"learnart\r\n" + 
			"specart\r\n" + 
			"animation\r\n" + 
			"wimmelbilder\r\n" + 
			"illustration\r\n" + 
			"streetart\r\n" + 
			"place\r\n" + 
			"breadstapledtotrees\r\n" + 
			"chairsunderwater\r\n" + 
			"painting\r\n" + 
			"minipainting\r\n" + 
			"gamedev\r\n" + 
			"engineering\r\n" + 
			"ubuntu\r\n" + 
			"cscareerquestions\r\n" + 
			"EngineeringStudents\r\n" + 
			"askengineers\r\n" + 
			"learnprogramming\r\n" + 
			"compsci\r\n" + 
			"java\r\n" + 
			"javascript\r\n" + 
			"coding\r\n" + 
			"machinelearning\r\n" + 
			"howtohack\r\n" + 
			"cpp\r\n" + 
			"artificial\r\n" + 
			"python\r\n" + 
			"learnpython\r\n" + 
			"Economics\r\n" + 
			"business\r\n" + 
			"entrepreneur\r\n" + 
			"marketing\r\n" + 
			"BasicIncome\r\n" + 
			"business\r\n" + 
			"smallbusiness\r\n" + 
			"stocks\r\n" + 
			"wallstreetbets\r\n" + 
			"stockmarket\r\n" + 
			"environment\r\n" + 
			"zerowaste\r\n" + 
			"history\r\n" + 
			"AskHistorians\r\n" + 
			"ColorizedHistory\r\n" + 
			"badhistory\r\n" + 
			"100yearsago\r\n" + 
			"HistoryPorn\r\n" + 
			"PropagandaPosters\r\n" + 
			"TheWayWeWere\r\n" + 
			"historymemes\r\n" + 
			"castles\r\n" + 
			"linguistics\r\n" + 
			"languagelearning\r\n" + 
			"learnjapanese\r\n" + 
			"french\r\n" + 
			"etymology\r\n" + 
			"law\r\n" + 
			"math\r\n" + 
			"theydidthemath\r\n" + 
			"medicalschool\r\n" + 
			"medizzy\r\n" + 
			"psychology\r\n" + 
			"Science\r\n" + 
			"AskScience\r\n" + 
			"cogsci\r\n" + 
			"medicine\r\n" + 
			"everythingscience\r\n" + 
			"geology\r\n" + 
			"Space\r\n" + 
			"SpacePorn\r\n" + 
			"astronomy\r\n" + 
			"astrophotography\r\n" + 
			"aliens\r\n" + 
			"rockets\r\n" + 
			"spacex\r\n" + 
			"nasa\r\n" + 
			"biology\r\n" + 
			"Awwducational\r\n" + 
			"chemicalreactiongifs\r\n" + 
			"chemistry\r\n" + 
			"physics\r\n" + 
			"entertainment\r\n" + 
			"fantheories\r\n" + 
			"Disney\r\n" + 
			"obscuremedia\r\n" + 
			"anime\r\n" + 
			"manga\r\n" + 
			"anime_irl\r\n" + 
			"awwnime\r\n" + 
			"TsundereSharks\r\n" + 
			"animesuggest\r\n" + 
			"animemes\r\n" + 
			"animegifs\r\n" + 
			"animewallpaper\r\n" + 
			"wholesomeanimemes\r\n" + 
			"pokemon\r\n" + 
			"onepiece\r\n" + 
			"naruto\r\n" + 
			"dbz\r\n" + 
			"onepunchman\r\n" + 
			"ShingekiNoKyojin\r\n" + 
			"yugioh\r\n" + 
			"BokuNoHeroAcademia\r\n" + 
			"DDLC\r\n" + 
			"berserk\r\n" + 
			"hunterxhunter\r\n" + 
			"tokyoghoul\r\n" + 
			"shitpostcrusaders\r\n" + 
			"Books\r\n" + 
			"WritingPrompts\r\n" + 
			"writing\r\n" + 
			"literature\r\n" + 
			"booksuggestions\r\n" + 
			"lifeofnorman\r\n" + 
			"poetry\r\n" + 
			"screenwriting\r\n" + 
			"freeEbooks\r\n" + 
			"boottoobig\r\n" + 
			"hfy\r\n" + 
			"suggestmeabook\r\n" + 
			"lovecraft\r\n" + 
			"comics\r\n" + 
			"comicbooks\r\n" + 
			"polandball\r\n" + 
			"marvel\r\n" + 
			"webcomics\r\n" + 
			"bertstrips\r\n" + 
			"marvelstudios\r\n" + 
			"defenders\r\n" + 
			"marvelmemes\r\n" + 
			"avengers\r\n" + 
			"harrypotter\r\n" + 
			"batman\r\n" + 
			"calvinandhobbes\r\n" + 
			"xkcd\r\n" + 
			"DCComics\r\n" + 
			"arrow\r\n" + 
			"unexpectedhogwarts\r\n" + 
			"spiderman\r\n" + 
			"deadpool\r\n" + 
			"KingkillerChronicle\r\n" + 
			"asoiaf\r\n" + 
			"gameofthrones\r\n" + 
			"freefolk\r\n" + 
			"jonwinsthethrone\r\n" + 
			"gameofthronesmemes\r\n" + 
			"daeneryswinsthethrone\r\n" + 
			"asongofmemesandrage\r\n" + 
			"lotr\r\n" + 
			"lotrmemes\r\n" + 
			"tolkienfans\r\n" + 
			"celebs\r\n" + 
			"celebhub\r\n" + 
			"EmmaWatson\r\n" + 
			"jessicanigri\r\n" + 
			"kateupton\r\n" + 
			"alisonbrie\r\n" + 
			"EmilyRatajkowski\r\n" + 
			"jenniferlawrence\r\n" + 
			"alexandradaddario\r\n" + 
			"onetruegod\r\n" + 
			"joerogan\r\n" + 
			"keanubeingawesome\r\n" + 
			"crewscrew\r\n" + 
			"donaldglover\r\n" + 
			"elonmusk\r\n" + 
			"cosplay\r\n" + 
			"cosplaygirls\r\n" + 
			"lego\r\n" + 
			"boardgames\r\n" + 
			"rpg\r\n" + 
			"chess\r\n" + 
			"poker\r\n" + 
			"jrpg\r\n" + 
			"DnD\r\n" + 
			"DnDGreentext\r\n" + 
			"DnDBehindTheScreen\r\n" + 
			"dndnext\r\n" + 
			"dungeonsanddragons\r\n" + 
			"criticalrole\r\n" + 
			"DMAcademy\r\n" + 
			"dndmemes\r\n" + 
			"magicTCG\r\n" + 
			"modernmagic\r\n" + 
			"magicarena\r\n" + 
			"zombies\r\n" + 
			"cyberpunk\r\n" + 
			"fantasy\r\n" + 
			"scifi\r\n" + 
			"starwars\r\n" + 
			"startrek\r\n" + 
			"asksciencefiction\r\n" + 
			"prequelmemes\r\n" + 
			"empiredidnothingwrong\r\n" + 
			"SequelMemes\r\n" + 
			"sciencefiction\r\n" + 
			"InternetIsBeautiful\r\n" + 
			"facepalm\r\n" + 
			"wikipedia\r\n" + 
			"creepyPMs\r\n" + 
			"web_design\r\n" + 
			"google\r\n" + 
			"KenM\r\n" + 
			"bannedfromclubpenguin\r\n" + 
			"savedyouaclick\r\n" + 
			"bestofworldstar\r\n" + 
			"discordapp\r\n" + 
			"snaplenses\r\n" + 
			"tronix\r\n" + 
			"instagramreality\r\n" + 
			"internetstars\r\n" + 
			"robinhood\r\n" + 
			"shortcuts\r\n" + 
			"scams\r\n" + 
			"tiktokcringe\r\n" + 
			"4chan\r\n" + 
			"Classic4chan\r\n" + 
			"greentext\r\n" + 
			"facepalm\r\n" + 
			"oldpeoplefacebook\r\n" + 
			"facebookwins\r\n" + 
			"indianpeoplefacebook\r\n" + 
			"terriblefacebookmemes\r\n" + 
			"insanepeoplefacebook\r\n" + 
			"Tinder\r\n" + 
			"OkCupid\r\n" + 
			"KotakuInAction\r\n" + 
			"wikileaks\r\n" + 
			"shitcosmosays\r\n" + 
			"twitch\r\n" + 
			"livestreamfail\r\n" + 
			"serialpodcast\r\n" + 
			"podcasts\r\n" + 
			"tumblrinaction\r\n" + 
			"tumblr\r\n" + 
			"blackpeopletwitter\r\n" + 
			"scottishpeopletwitter\r\n" + 
			"WhitePeopleTwitter\r\n" + 
			"wholesomebpt\r\n" + 
			"latinopeopletwitter\r\n" + 
			"YoutubeHaiku\r\n" + 
			"youtube\r\n" + 
			"youngpeopleyoutube\r\n" + 
			"gamegrumps\r\n" + 
			"h3h3productions\r\n" + 
			"CGPGrey\r\n" + 
			"yogscast\r\n" + 
			"jontron\r\n" + 
			"Idubbbz\r\n" + 
			"defranco\r\n" + 
			"cynicalbrit\r\n" + 
			"pyrocynical\r\n" + 
			"SovietWomble\r\n" + 
			"RedLetterMedia\r\n" + 
			"videogamedunkey\r\n" + 
			"loltyler1\r\n" + 
			"ksi\r\n" + 
			"MiniLadd\r\n" + 
			"pewdiepiesubmissions\r\n" + 
			"pewdiepie\r\n" + 
			"roosterteeth\r\n" + 
			"funhaus\r\n" + 
			"rwby\r\n" + 
			"cowchop\r\n" + 
			"movies\r\n" + 
			"documentaries\r\n" + 
			"fullmoviesonyoutube\r\n" + 
			"truefilm\r\n" + 
			"bollywoodrealism\r\n" + 
			"moviedetails\r\n" + 
			"moviesinthemaking\r\n" + 
			"fullmoviesonvimeo\r\n" + 
			"continuityporn\r\n" + 
			"ghibli\r\n" + 
			"cinematography\r\n" + 
			"shittymoviedetails\r\n" + 
			"moviescirclejerk\r\n" + 
			"starwars\r\n" + 
			"harrypotter\r\n" + 
			"lotr\r\n" + 
			"lotrmemes\r\n" + 
			"otmemes\r\n" + 
			"marvelstudios\r\n" + 
			"batman\r\n" + 
			"DC_Cinematic\r\n" + 
			"thanosdidnothingwrong\r\n" + 
			"inthesoulstone\r\n" + 
			"music\r\n" + 
			"listentothis\r\n" + 
			"WeAreTheMusicMakers\r\n" + 
			"mashups\r\n" + 
			"vinyl\r\n" + 
			"futurebeats\r\n" + 
			"musictheory\r\n" + 
			"guitarlessons\r\n" + 
			"spotify\r\n" + 
			"fakealbumcovers\r\n" + 
			"ableton\r\n" + 
			"kanye\r\n" + 
			"radiohead\r\n" + 
			"KendrickLamar\r\n" + 
			"gorillaz\r\n" + 
			"frankocean\r\n" + 
			"donaldglover\r\n" + 
			"eminem\r\n" + 
			"brockhampton\r\n" + 
			"beatles\r\n" + 
			"deathgrips\r\n" + 
			"pinkfloyd\r\n" + 
			"classicalmusic\r\n" + 
			"jazz\r\n" + 
			"trap\r\n" + 
			"indieheads\r\n" + 
			"gamemusic\r\n" + 
			"outrun\r\n" + 
			"vaporwave\r\n" + 
			"dubstep\r\n" + 
			"electronicmusic\r\n" + 
			"edmproduction\r\n" + 
			"EDM\r\n" + 
			"hiphopheads\r\n" + 
			"hiphopimages\r\n" + 
			"Metal\r\n" + 
			"Metalcore\r\n" + 
			"spop\r\n" + 
			"kpop\r\n" + 
			"funkopop\r\n" + 
			"popheads\r\n" + 
			"guitar\r\n" + 
			"piano\r\n" + 
			"bass\r\n" + 
			"drums\r\n" + 
			"sports\r\n" + 
			"running\r\n" + 
			"bicycling\r\n" + 
			"golf\r\n" + 
			"fishing\r\n" + 
			"skiing\r\n" + 
			"sportsarefun\r\n" + 
			"tennis\r\n" + 
			"rugbyunion\r\n" + 
			"discgolf\r\n" + 
			"cricket\r\n" + 
			"sailing\r\n" + 
			"nfl\r\n" + 
			"CFB\r\n" + 
			"fantasyfootball\r\n" + 
			"nflstreams\r\n" + 
			"patriots\r\n" + 
			"eagles\r\n" + 
			"greenbaypackers\r\n" + 
			"minnesotavikings\r\n" + 
			"losangelesrams\r\n" + 
			"baseball\r\n" + 
			"mlb\r\n" + 
			"fantasybaseball\r\n" + 
			"nba\r\n" + 
			"collegebasketball\r\n" + 
			"nbastreams\r\n" + 
			"fantasybball\r\n" + 
			"warriors\r\n" + 
			"lakers\r\n" + 
			"bostonceltics\r\n" + 
			"torontoraptors\r\n" + 
			"sixers\r\n" + 
			"chicagobulls\r\n" + 
			"skateboarding\r\n" + 
			"snowboarding\r\n" + 
			"longboarding\r\n" + 
			"formula1\r\n" + 
			"Nascar\r\n" + 
			"MMA\r\n" + 
			"squaredcircle\r\n" + 
			"theocho\r\n" + 
			"ufc\r\n" + 
			"boxing\r\n" + 
			"wwe\r\n" + 
			"MMAStreams\r\n" + 
			"hockey\r\n" + 
			"nhl\r\n" + 
			"nhlstreams\r\n" + 
			"leafs\r\n" + 
			"olympics\r\n" + 
			"apocalympics2016\r\n" + 
			"soccer\r\n" + 
			"worldcup\r\n" + 
			"Bundesliga\r\n" + 
			"futbol\r\n" + 
			"soccerstreams\r\n" + 
			"MLS\r\n" + 
			"fantasypl\r\n" + 
			"gunners\r\n" + 
			"reddevils\r\n" + 
			"LiverpoolFC\r\n" + 
			"chelseafc\r\n" + 
			"Television\r\n" + 
			"marvelstudios\r\n" + 
			"japanesegameshows\r\n" + 
			"shield\r\n" + 
			"cordcutters\r\n" + 
			"offlinetv\r\n" + 
			"tvdetails\r\n" + 
			"GameOfThrones\r\n" + 
			"BreakingBad\r\n" + 
			"thewalkingdead\r\n" + 
			"community\r\n" + 
			"arresteddevelopment\r\n" + 
			"topgear\r\n" + 
			"StarTrek\r\n" + 
			"HIMYM\r\n" + 
			"firefly\r\n" + 
			"PandR\r\n" + 
			"Sherlock\r\n" + 
			"DunderMifflin\r\n" + 
			"BetterCallSaul\r\n" + 
			"TrueDetective\r\n" + 
			"houseofcards\r\n" + 
			"MakingaMurderer\r\n" + 
			"FlashTV\r\n" + 
			"trailerparkboys\r\n" + 
			"mrrobot\r\n" + 
			"siliconvalleyhbo\r\n" + 
			"strangerthings\r\n" + 
			"supernatural\r\n" + 
			"thegrandtour\r\n" + 
			"AmericanHorrorStory\r\n" + 
			"rupaulsdragrace\r\n" + 
			"westworld\r\n" + 
			"blackmirror\r\n" + 
			"FilthyFrank\r\n" + 
			"orangeisthenewblack\r\n" + 
			"twinpeaks\r\n" + 
			"bigbrother\r\n" + 
			"brooklynninenine\r\n" + 
			"scrubs\r\n" + 
			"howyoudoin\r\n" + 
			"30rock\r\n" + 
			"lifeisstrange\r\n" + 
			"survivor\r\n" + 
			"riverdale\r\n" + 
			"letterkenny\r\n" + 
			"Pokemon\r\n" + 
			"AdventureTime\r\n" + 
			"futurama\r\n" + 
			"TheLastAirbender\r\n" + 
			"ArcherFX\r\n" + 
			"southpark\r\n" + 
			"TheSimpsons\r\n" + 
			"mylittlepony\r\n" + 
			"rickandmorty\r\n" + 
			"naruto\r\n" + 
			"stevenuniverse\r\n" + 
			"onepunchman\r\n" + 
			"BobsBurgers\r\n" + 
			"BoJackHorseman\r\n" + 
			"gravityfalls\r\n" + 
			"familyguy\r\n" + 
			"kingofthehill\r\n" + 
			"spongebob\r\n" + 
			"dbz\r\n" + 
			"DBZDokkanBattle\r\n" + 
			"dragonballfighterz\r\n" + 
			"doctorwho\r\n" + 
			"gallifrey\r\n" + 
			"IASIP\r\n" + 
			"the_dennis\r\n" + 
			"seinfeld\r\n" + 
			"redditwritesseinfeld\r\n" + 
			"seinfeldgifs\r\n" + 
			"NetflixBestOf\r\n" + 
			"Netflix\r\n" + 
			"bestofnetflix\r\n" + 
			"DIY\r\n" + 
			"cosplay\r\n" + 
			"woodworking\r\n" + 
			"somethingimade\r\n" + 
			"architecture\r\n" + 
			"CoolGuides\r\n" + 
			"WorldBuilding\r\n" + 
			"ifyoulikeblank\r\n" + 
			"DiWHY\r\n" + 
			"knitting\r\n" + 
			"sewing\r\n" + 
			"modelmakers\r\n" + 
			"crochet\r\n" + 
			"ProtectAndServe\r\n" + 
			"RTLSDR\r\n" + 
			"digitalnomad\r\n" + 
			"FastWorkers\r\n" + 
			"accounting\r\n" + 
			"preppers\r\n" + 
			"redneckengineering\r\n" + 
			"crossstitch\r\n" + 
			"dumpsterdiving\r\n" + 
			"gunpla\r\n" + 
			"urbanplanning\r\n" + 
			"cubers\r\n" + 
			"blacksmith\r\n" + 
			"toptalent\r\n" + 
			"slavelabour\r\n" + 
			"aquariums\r\n" + 
			"plantedtank\r\n" + 
			"art\r\n" + 
			"Drawing\r\n" + 
			"crafts\r\n" + 
			"alternativeart\r\n" + 
			"sketchdaily\r\n" + 
			"artporn\r\n" + 
			"glitch_art\r\n" + 
			"coloringcorruptions\r\n" + 
			"restofthefuckingowl\r\n" + 
			"DisneyVacation\r\n" + 
			"illustration\r\n" + 
			"Writing\r\n" + 
			"writingprompts\r\n" + 
			"screenwriting\r\n" + 
			"fountainpens\r\n" + 
			"calligraphy\r\n" + 
			"handwriting\r\n" + 
			"twosentencehorror\r\n" + 
			"brandnewsentence\r\n" + 
			"cars\r\n" + 
			"motorcycles\r\n" + 
			"carporn\r\n" + 
			"justrolledintotheshop\r\n" + 
			"idiotsincars\r\n" + 
			"Shitty_Car_Mods\r\n" + 
			"autos\r\n" + 
			"roadcam\r\n" + 
			"AutoDetailing\r\n" + 
			"awesomecarmods\r\n" + 
			"projectcar\r\n" + 
			"cartalk\r\n" + 
			"tiresaretheenemy\r\n" + 
			"roadtrip\r\n" + 
			"convenientcop\r\n" + 
			"dashcamgifs\r\n" + 
			"subaru\r\n" + 
			"teslamotors\r\n" + 
			"bmw\r\n" + 
			"jeep\r\n" + 
			"CrappyDesign\r\n" + 
			"web_design\r\n" + 
			"graphic_design\r\n" + 
			"design\r\n" + 
			"designporn\r\n" + 
			"InteriorDesign\r\n" + 
			"ATBGE\r\n" + 
			"dontdeadopeninside\r\n" + 
			"assholedesign\r\n" + 
			"keming\r\n" + 
			"logodesign\r\n" + 
			"tombstoning\r\n" + 
			"dangerousdesign\r\n" + 
			"actlikeyoubelong\r\n" + 
			"irlsmurfing\r\n" + 
			"MilitaryPorn\r\n" + 
			"military\r\n" + 
			"combatfootage\r\n" + 
			"militarygfys\r\n" + 
			"army\r\n" + 
			"warshipporn\r\n" + 
			"justbootthings\r\n" + 
			"guns\r\n" + 
			"gunporn\r\n" + 
			"gundeals\r\n" + 
			"ar15\r\n" + 
			"firearms\r\n" + 
			"ccw\r\n" + 
			"airsoft\r\n" + 
			"Jobs\r\n" + 
			"forhire\r\n" + 
			"cscareerquestions\r\n" + 
			"workonline\r\n" + 
			"guitar\r\n" + 
			"WeAreTheMusicMakers\r\n" + 
			"edmproduction\r\n" + 
			"piano\r\n" + 
			"ableton\r\n" + 
			"drums\r\n" + 
			"FL_Studio\r\n" + 
			"urbanexploration\r\n" + 
			"survival\r\n" + 
			"backpacking\r\n" + 
			"camping\r\n" + 
			"homestead\r\n" + 
			"MTB\r\n" + 
			"outdoors\r\n" + 
			"wildernessbackpacking\r\n" + 
			"campinggear\r\n" + 
			"bushcraft\r\n" + 
			"gardening\r\n" + 
			"indoorgarden\r\n" + 
			"campingandhiking\r\n" + 
			"hiking\r\n" + 
			"ultralight\r\n" + 
			"photography\r\n" + 
			"itookapicture\r\n" + 
			"Filmmakers\r\n" + 
			"astrophotography\r\n" + 
			"analog\r\n" + 
			"photocritique\r\n" + 
			"postprocessing\r\n" + 
			"aviation\r\n" + 
			"flying\r\n" + 
			"sysadmin\r\n" + 
			"engineering\r\n" + 
			"compsci\r\n" + 
			"webdev\r\n" + 
			"programmerhumor\r\n" + 
			"graphic_design\r\n" + 
			"mechanicalkeyboards\r\n" + 
			"reverseengineering\r\n" + 
			"itsaunixsystem\r\n" + 
			"plex\r\n" + 
			"multicopter\r\n" + 
			"programminghorror\r\n" + 
			"dailyprogrammer\r\n" + 
			"coding\r\n" + 
			"python\r\n" + 
			"java\r\n" + 
			"cpp\r\n" + 
			"security\r\n" + 
			"buildapc\r\n" + 
			"buildapcsales\r\n" + 
			"buildapcforme\r\n" + 
			"talesfromtechsupport\r\n" + 
			"techsupportgore\r\n" + 
			"techsupport\r\n" + 
			"softwaregore\r\n" + 
			"iiiiiiitttttttttttt\r\n" + 
			"watches\r\n" + 
			"lockpicking\r\n" + 
			"knives\r\n" + 
			"specializedtools\r\n" + 
			"knifeclub\r\n" + 
			"travel\r\n" + 
			"solotravel\r\n" + 
			"japantravel\r\n" + 
			"shoestring\r\n" + 
			"LifeProTips\r\n" + 
			"lifehacks\r\n" + 
			"geek\r\n" + 
			"EDC\r\n" + 
			"simpleliving\r\n" + 
			"tinyhouses\r\n" + 
			"rainmeter\r\n" + 
			"vandwellers\r\n" + 
			"UnethicalLifeProTips\r\n" + 
			"vagabond\r\n" + 
			"illegallifeprotips\r\n" + 
			"malelifestyle\r\n" + 
			"malelivingspace\r\n" + 
			"TheGirlSurvivalGuide\r\n" + 
			"homeimprovement\r\n" + 
			"homelab\r\n" + 
			"homeautomation\r\n" + 
			"battlestations\r\n" + 
			"hometheater\r\n" + 
			"teenagers\r\n" + 
			"introvert\r\n" + 
			"ADHD\r\n" + 
			"totallynotrobots\r\n" + 
			"polyamory\r\n" + 
			"teachers\r\n" + 
			"aliensamongus\r\n" + 
			"neverbrokeabone\r\n" + 
			"bipolar\r\n" + 
			"beards\r\n" + 
			"vegan\r\n" + 
			"swoleacceptance\r\n" + 
			"tall\r\n" + 
			"lgbt\r\n" + 
			"gaybros\r\n" + 
			"actuallesbians\r\n" + 
			"gaymers\r\n" + 
			"bisexual\r\n" + 
			"askgaybros\r\n" + 
			"ainbow\r\n" + 
			"gay\r\n" + 
			"gay_irl\r\n" + 
			"asktransgender\r\n" + 
			"transgender\r\n" + 
			"parenting\r\n" + 
			"daddit\r\n" + 
			"babybumps\r\n" + 
			"drunk\r\n" + 
			"scotch\r\n" + 
			"stopdrinking\r\n" + 
			"cocktails\r\n" + 
			"wine\r\n" + 
			"bourbon\r\n" + 
			"whiskey\r\n" + 
			"beer\r\n" + 
			"homebrewing\r\n" + 
			"showerbeer\r\n" + 
			"beerporn\r\n" + 
			"trees\r\n" + 
			"marijuana\r\n" + 
			"microgrowery\r\n" + 
			"eldertrees\r\n" + 
			"see\r\n" + 
			"leaves\r\n" + 
			"weed\r\n" + 
			"weedstocks\r\n" + 
			"cannabis\r\n" + 
			"drugs\r\n" + 
			"electronic_cigarette\r\n" + 
			"stonerengineering\r\n" + 
			"Nootropics\r\n" + 
			"LSD\r\n" + 
			"vaporents\r\n" + 
			"Vaping\r\n" + 
			"stopsmoking\r\n" + 
			"shrooms\r\n" + 
			"dmt\r\n" + 
			"GetMotivated\r\n" + 
			"health\r\n" + 
			"ZenHabits\r\n" + 
			"Medicine\r\n" + 
			"motivation\r\n" + 
			"LucidDreaming\r\n" + 
			"meditation\r\n" + 
			"Psychonaut\r\n" + 
			"mentalhealth\r\n" + 
			"Fitness\r\n" + 
			"xxfitness\r\n" + 
			"fitmeals\r\n" + 
			"paleo\r\n" + 
			"nutrition\r\n" + 
			"vegetarian\r\n" + 
			"leangains\r\n" + 
			"HealthyFood\r\n" + 
			"intermittentfasting\r\n" + 
			"fasting\r\n" + 
			"keto\r\n" + 
			"ketorecipes\r\n" + 
			"ketogains\r\n" + 
			"bicycling\r\n" + 
			"yoga\r\n" + 
			"skateboarding\r\n" + 
			"climbing\r\n" + 
			"backpacking\r\n" + 
			"bjj\r\n" + 
			"skiing\r\n" + 
			"crossfit\r\n" + 
			"bodybuilding\r\n" + 
			"WeightRoom\r\n" + 
			"powerlifting\r\n" + 
			"running\r\n" + 
			"c25k\r\n" + 
			"loseit\r\n" + 
			"bodyweightfitness\r\n" + 
			"gainit\r\n" + 
			"swoleacceptance\r\n" + 
			"flexibility\r\n" + 
			"progresspics\r\n" + 
			"brogress\r\n" + 
			"makeupaddiction\r\n" + 
			"SkincareAddiction\r\n" + 
			"beards\r\n" + 
			"wicked_edge\r\n" + 
			"RedditLaqueristas\r\n" + 
			"AsianBeauty\r\n" + 
			"piercing\r\n" + 
			"FancyFollicles\r\n" + 
			"malehairadvice\r\n" + 
			"curlyhair\r\n" + 
			"tattoos\r\n" + 
			"badtattoos\r\n" + 
			"tattoo\r\n" + 
			"malefashionadvice\r\n" + 
			"frugalmalefashion\r\n" + 
			"femalefashionadvice\r\n" + 
			"thriftstorehauls\r\n" + 
			"fashion\r\n" + 
			"streetwear\r\n" + 
			"malefashion\r\n" + 
			"supremeclothing\r\n" + 
			"FashionReps\r\n" + 
			"designerreps\r\n" + 
			"sneakers\r\n" + 
			"repsneakers\r\n" + 
			"goodyearwelt\r\n" + 
			"food\r\n" + 
			"FoodPorn\r\n" + 
			"foodhacks\r\n" + 
			"shittyfoodporn\r\n" + 
			"eatsandwiches\r\n" + 
			"nutrition\r\n" + 
			"mealtimevideos\r\n" + 
			"WeWantPlates\r\n" + 
			"forbiddensnacks\r\n" + 
			"seriouseats\r\n" + 
			"spicy\r\n" + 
			"cooking\r\n" + 
			"slowcooking\r\n" + 
			"askculinary\r\n" + 
			"baking\r\n" + 
			"mealprepsunday\r\n" + 
			"breadit\r\n" + 
			"cookingforbeginners\r\n" + 
			"smoking\r\n" + 
			"castiron\r\n" + 
			"instantpot\r\n" + 
			"sousvide\r\n" + 
			"EatCheapAndHealthy\r\n" + 
			"fitmeals\r\n" + 
			"budgetfood\r\n" + 
			"ketorecipes\r\n" + 
			"vegan\r\n" + 
			"1200isplenty\r\n" + 
			"Cheap_Meals\r\n" + 
			"HealthyFood\r\n" + 
			"veganrecipes\r\n" + 
			"intermittentfasting\r\n" + 
			"fasting\r\n" + 
			"coffee\r\n" + 
			"tea\r\n" + 
			"recipes\r\n" + 
			"gifrecipes\r\n" + 
			"veganrecipes\r\n" + 
			"pizza\r\n" + 
			"grilledcheese\r\n" + 
			"ramen\r\n" + 
			"bbq\r\n" + 
			"sushi\r\n" + 
			"PersonalFinance\r\n" + 
			"Entrepreneur\r\n" + 
			"beermoney\r\n" + 
			"startups\r\n" + 
			"finance\r\n" + 
			"economy\r\n" + 
			"financialindependence\r\n" + 
			"apphookup\r\n" + 
			"churning\r\n" + 
			"realestate\r\n" + 
			"flipping\r\n" + 
			"antimlm\r\n" + 
			"ripple\r\n" + 
			"Iota\r\n" + 
			"stellar\r\n" + 
			"personalfinancecanada\r\n" + 
			"investing\r\n" + 
			"wallstreetbets\r\n" + 
			"millionairemakers\r\n" + 
			"weedstocks\r\n" + 
			"frugal\r\n" + 
			"EatCheapAndHealthy\r\n" + 
			"frugalmalefashion\r\n" + 
			"budgetfood\r\n" + 
			"cheap_meals\r\n" + 
			"Frugal_Jerk\r\n" + 
			"povertyfinance\r\n" + 
			"shutupandtakemymoney\r\n" + 
			"BuyItForLife\r\n" + 
			"crappyoffbrands\r\n" + 
			"shouldibuythisgame\r\n" + 
			"Anticonsumption\r\n" + 
			"sbubby\r\n" + 
			"Wellworn\r\n" + 
			"ineeeedit\r\n" + 
			"didntknowiwantedthat\r\n" + 
			"Bitcoin\r\n" + 
			"dogecoin\r\n" + 
			"CryptoCurrency\r\n" + 
			"ethereum\r\n" + 
			"ethtrade\r\n" + 
			"litecoin\r\n" + 
			"btc\r\n" + 
			"garlicoin\r\n" + 
			"cardano\r\n" + 
			"Vechain\r\n" + 
			"Psychonaut\r\n" + 
			"Buddhism\r\n" + 
			"Stoicism\r\n" + 
			"occult\r\n" + 
			"atheism\r\n" + 
			"trueatheism\r\n" + 
			"Christianity\r\n" + 
			"dankchristianmemes\r\n" + 
			"exmormon\r\n" + 
			"Catholicism\r\n" + 
			"philosophy\r\n" + 
			"askphilosophy\r\n" + 
			"socialskills\r\n" + 
			"socialengineering\r\n" + 
			"weddingplanning\r\n" + 
			"Parenting\r\n" + 
			"childfree\r\n" + 
			"raisedbynarcissists\r\n" + 
			"incest\r\n" + 
			"daddit\r\n" + 
			"justnomil\r\n" + 
			"justnofamily\r\n" + 
			"relationships\r\n" + 
			"relationship_advice\r\n" + 
			"dating_advice\r\n" + 
			"breakups\r\n" + 
			"Tinder\r\n" + 
			"OKCupid\r\n" + 
			"r4r\r\n" + 
			"dirtyr4r\r\n" + 
			"longdistance\r\n" + 
			"sex\r\n" + 
			"seduction\r\n" + 
			"nofap\r\n" + 
			"deadbedrooms\r\n" + 
			"polyamory\r\n" + 
			"GetMotivated\r\n" + 
			"QuotesPorn\r\n" + 
			"getdisciplined\r\n" + 
			"happy\r\n" + 
			"productivity\r\n" + 
			"DecidingToBeBetter\r\n" + 
			"mademesmile\r\n" + 
			"selfimprovement\r\n" + 
			"iwantout\r\n" + 
			"humansbeingbros\r\n" + 
			"happycrowds\r\n" + 
			"sportsarefun\r\n" + 
			"GetStudying\r\n" + 
			"motivation\r\n" + 
			"gatesopencomeonin\r\n" + 
			"technology\r\n" + 
			"internetisbeautiful\r\n" + 
			"futurology\r\n" + 
			"pcmasterrace\r\n" + 
			"buildapc\r\n" + 
			"talesfromtechsupport\r\n" + 
			"netsec\r\n" + 
			"gamedev\r\n" + 
			"design\r\n" + 
			"engineering\r\n" + 
			"jailbreak\r\n" + 
			"compsci\r\n" + 
			"tech\r\n" + 
			"hacking\r\n" + 
			"imaginarytechnology\r\n" + 
			"privacy\r\n" + 
			"torrents\r\n" + 
			"networking\r\n" + 
			"infographics\r\n" + 
			"piracy\r\n" + 
			"EngineeringPorn\r\n" + 
			"cableporn\r\n" + 
			"simulated\r\n" + 
			"onions\r\n" + 
			"unixporn\r\n" + 
			"crackwatch\r\n" + 
			"php\r\n" + 
			"aboringdystopia\r\n" + 
			"virtualreality\r\n" + 
			"opensource\r\n" + 
			"3Dprinting\r\n" + 
			"functionalprint\r\n" + 
			"nintendo\r\n" + 
			"spacex\r\n" + 
			"nasa\r\n" + 
			"amd\r\n" + 
			"nvidia\r\n" + 
			"photoshop\r\n" + 
			"firefox\r\n" + 
			"Android\r\n" + 
			"AndroidApps\r\n" + 
			"AndroidGaming\r\n" + 
			"AndroidDev\r\n" + 
			"AndroidThemes\r\n" + 
			"oneplus\r\n" + 
			"apple\r\n" + 
			"iphone\r\n" + 
			"mac\r\n" + 
			"ipad\r\n" + 
			"applewatch\r\n" + 
			"gadgets\r\n" + 
			"raspberry_pi\r\n" + 
			"electronics\r\n" + 
			"arduino\r\n" + 
			"trackers\r\n" + 
			"gopro\r\n" + 
			"blender\r\n" + 
			"amazonecho\r\n" + 
			"RetroPie\r\n" + 
			"hardware\r\n" + 
			"hardwareswap\r\n" + 
			"Addons4Kodi\r\n" + 
			"kodi\r\n" + 
			"google\r\n" + 
			"chromecast\r\n" + 
			"googlepixel\r\n" + 
			"googlehome\r\n" + 
			"linux\r\n" + 
			"linux_gaming\r\n" + 
			"linux4noobs\r\n" + 
			"linuxmasterrace\r\n" + 
			"archlinux\r\n" + 
			"Windows10\r\n" + 
			"windows\r\n" + 
			"excel\r\n" + 
			"surface\r\n" + 
			"microsoft\r\n" + 
			"dataisbeautiful\r\n" + 
			"DataHoarder\r\n" + 
			"datascience\r\n" + 
			"Bitcoin\r\n" + 
			"dogecoin\r\n" + 
			"CryptoCurrency\r\n" + 
			"ethereum\r\n" + 
			"ethtrader\r\n" + 
			"btc\r\n" + 
			"litecoin\r\n" + 
			"bitcoinmarkets\r\n" + 
			"cryptomarkets\r\n" + 
			"monero\r\n" + 
			"neo\r\n" + 
			"programming\r\n" + 
			"learnprogramming\r\n" + 
			"python\r\n" + 
			"java\r\n" + 
			"javascript\r\n" + 
			"learnpython\r\n" + 
			"excel\r\n" + 
			"unity3d\r\n" + 
			"reactjs\r\n" + 
			"audiophile\r\n" + 
			"headphones\r\n" + 
			"audioengineering\r\n" + 
			"funny\r\n" + 
			"humor\r\n" + 
			"contagiouslaughter\r\n" + 
			"standupcomedy\r\n" + 
			"ProgrammerHumor\r\n" + 
			"prematurecelebration\r\n" + 
			"ChildrenFallingOver\r\n" + 
			"dadreflexes\r\n" + 
			"kenm\r\n" + 
			"politicalhumor\r\n" + 
			"accidentalcomedy\r\n" + 
			"funnyandsad\r\n" + 
			"kidsarefuckingstupid\r\n" + 
			"notkenm\r\n" + 
			"suspiciouslyspecific\r\n" + 
			"oddlyspecific\r\n" + 
			"rimjob_steve\r\n" + 
			"dark_humor\r\n" + 
			"stepdadreflexes\r\n" + 
			"congratslikeimfive\r\n" + 
			"darkhumorandmemes\r\n" + 
			"ComedyCemetery\r\n" + 
			"comedyheaven\r\n" + 
			"comedynecromancy\r\n" + 
			"comedyhomicide\r\n" + 
			"comedynecrophilia\r\n" + 
			"Jokes\r\n" + 
			"dadjokes\r\n" + 
			"standupshots\r\n" + 
			"punny\r\n" + 
			"antijokes\r\n" + 
			"meanjokes\r\n" + 
			"3amjokes\r\n" + 
			"puns\r\n" + 
			"WordAvalanches\r\n" + 
			"darkjokes\r\n" + 
			"AnimalsBeingJerks\r\n" + 
			"AnimalsBeingBros\r\n" + 
			"AnimalPorn\r\n" + 
			"AnimalsBeingDerps\r\n" + 
			"likeus\r\n" + 
			"stoppedworking\r\n" + 
			"hitmanimals\r\n" + 
			"animaltextgifs\r\n" + 
			"BeforeNAfterAdoption\r\n" + 
			"sneks\r\n" + 
			"TsundereSharks\r\n" + 
			"whatsthisbug\r\n" + 
			"HybridAnimals\r\n" + 
			"zoomies\r\n" + 
			"brushybrushy\r\n" + 
			"bigboye\r\n" + 
			"curledfeetsies\r\n" + 
			"mlem\r\n" + 
			"Floof\r\n" + 
			"shittyanimalfacts\r\n" + 
			"animalsthatlovemagic\r\n" + 
			"spiderbro\r\n" + 
			"properanimalnames\r\n" + 
			"reverseanimalrescue\r\n" + 
			"animalsdoingstuff\r\n" + 
			"sploot\r\n" + 
			"birdswitharms\r\n" + 
			"superbowl\r\n" + 
			"birbs\r\n" + 
			"partyparrot\r\n" + 
			"birdsbeingdicks\r\n" + 
			"emuwarflashbacks\r\n" + 
			"birdsarentreal\r\n" + 
			"babyelephantgifs\r\n" + 
			"sloths\r\n" + 
			"foxes\r\n" + 
			"trashpandas\r\n" + 
			"happycowgifs\r\n" + 
			"rabbits\r\n" + 
			"goatparkour\r\n" + 
			"bearsdoinghumanthings\r\n" + 
			"cats\r\n" + 
			"startledcats\r\n" + 
			"catpictures\r\n" + 
			"catsstandingup\r\n" + 
			"catpranks\r\n" + 
			"meow_irl\r\n" + 
			"holdmycatnip\r\n" + 
			"catslaps\r\n" + 
			"thecatdimension\r\n" + 
			"babybigcatgifs\r\n" + 
			"catloaf\r\n" + 
			"thisismylifemeow\r\n" + 
			"cattaps\r\n" + 
			"teefies\r\n" + 
			"tuckedinkitties\r\n" + 
			"catsareassholes\r\n" + 
			"catsisuottatfo\r\n" + 
			"stuffoncats\r\n" + 
			"bigcatgifs\r\n" + 
			"jellybeantoes\r\n" + 
			"catsareliquid\r\n" + 
			"catgifs\r\n" + 
			"blackcats\r\n" + 
			"supermodelcats\r\n" + 
			"chonkers\r\n" + 
			"tightpussy\r\n" + 
			"catswithjobs\r\n" + 
			"catswhoyell\r\n" + 
			"whatswrongwithyourcat\r\n" + 
			"dogs\r\n" + 
			"dogpictures\r\n" + 
			"dogtraining\r\n" + 
			"woof_irl\r\n" + 
			"WhatsWrongWithYourDog\r\n" + 
			"dogberg\r\n" + 
			"dogswithjobs\r\n" + 
			"masterreturns\r\n" + 
			"barkour\r\n" + 
			"blop\r\n" + 
			"puppysmiles\r\n" + 
			"puppies\r\n" + 
			"petthedamndog\r\n" + 
			"corgi\r\n" + 
			"Pitbulls\r\n" + 
			"goldenretrievers\r\n" + 
			"incorgnito\r\n" + 
			"babycorgis\r\n" + 
			"conspiracy\r\n" + 
			"skeptic\r\n" + 
			"karmaconspiracy\r\n" + 
			"UFOs\r\n" + 
			"conspiratard\r\n" + 
			"empiredidnothingwrong\r\n" + 
			"scp\r\n" + 
			"birdsarentreal\r\n" + 
			"cringepics\r\n" + 
			"cringe\r\n" + 
			"instant_regret\r\n" + 
			"blunderyears\r\n" + 
			"facepalm\r\n" + 
			"fatlogic\r\n" + 
			"publicfreakout\r\n" + 
			"lewronggeneration\r\n" + 
			"fellowkids\r\n" + 
			"sadcringe\r\n" + 
			"corporatefacepalm\r\n" + 
			"4PanelCringe\r\n" + 
			"amibeingdetained\r\n" + 
			"instantbarbarians\r\n" + 
			"watchpeopledieinside\r\n" + 
			"technicallythetruth\r\n" + 
			"accidentalracism\r\n" + 
			"engrish\r\n" + 
			"wokekids\r\n" + 
			"masterhacker\r\n" + 
			"cringetopia\r\n" + 
			"holup\r\n" + 
			"agedlikemilk\r\n" + 
			"tiktokcringe\r\n" + 
			"facepalm\r\n" + 
			"quityourbullshit\r\n" + 
			"thathappened\r\n" + 
			"delusionalartists\r\n" + 
			"oopsdidntmeanto\r\n" + 
			"beholdthemasterrace\r\n" + 
			"murderedbywords\r\n" + 
			"ihavesex\r\n" + 
			"woooosh\r\n" + 
			"badfaketexts\r\n" + 
			"boneappletea\r\n" + 
			"atetheonion\r\n" + 
			"iamatotalpieceofshit\r\n" + 
			"suicidebywords\r\n" + 
			"kamikazebywords\r\n" + 
			"wowthanksimcured\r\n" + 
			"topmindsofreddit\r\n" + 
			"lostredditors\r\n" + 
			"dontyouknowwhoiam\r\n" + 
			"NobodyAsked\r\n" + 
			"dontfundme\r\n" + 
			"nothingeverhappens\r\n" + 
			"vaxxhappened\r\n" + 
			"goodfaketexts\r\n" + 
			"delusionalcraigslist\r\n" + 
			"suspiciousquotes\r\n" + 
			"facingtheirparenting\r\n" + 
			"ihadastroke\r\n" + 
			"untrustworthypoptarts\r\n" + 
			"phonesarebad\r\n" + 
			"rareinsults\r\n" + 
			"clevercomebacks\r\n" + 
			"fuckyoukaren\r\n" + 
			"uselessredcircle\r\n" + 
			"niceguys\r\n" + 
			"mallninjashit\r\n" + 
			"ChoosingBeggars\r\n" + 
			"gatekeeping\r\n" + 
			"creepyasterisks\r\n" + 
			"inceltears\r\n" + 
			"humblebrag\r\n" + 
			"nothowdrugswork\r\n" + 
			"whiteknighting\r\n" + 
			"neckbeardrpg\r\n" + 
			"virginsvschad\r\n" + 
			"nicegirls\r\n" + 
			"notliketheothergirls\r\n" + 
			"notlikeothergirls\r\n" + 
			"entitledbitch\r\n" + 
			"iamverysmart\r\n" + 
			"iamverybadass\r\n" + 
			"iamveryrandom\r\n" + 
			"imveryedgy\r\n" + 
			"justneckbeardthings\r\n" + 
			"neckbeardnests\r\n" + 
			"entitledparents\r\n" + 
			"insaneparents\r\n" + 
			"shitmomgroupssay\r\n" + 
			"aww\r\n" + 
			"cats\r\n" + 
			"animalsbeingjerks\r\n" + 
			"animalsbeingbros\r\n" + 
			"Awwducational\r\n" + 
			"dogs\r\n" + 
			"corgi\r\n" + 
			"thisismylifenow\r\n" + 
			"blep\r\n" + 
			"eyebeach\r\n" + 
			"tippytaps\r\n" + 
			"awww\r\n" + 
			"babycorgis\r\n" + 
			"WTF\r\n" + 
			"DeepIntoYouTube\r\n" + 
			"fifthworldproblems\r\n" + 
			"awwwtf\r\n" + 
			"wellthatsucks\r\n" + 
			"streetfights\r\n" + 
			"yesyesyesyesno\r\n" + 
			"wtfstockphotos\r\n" + 
			"yesyesyesno\r\n" + 
			"maybemaybemaybe\r\n" + 
			"oddlyterrifying\r\n" + 
			"thatlookedexpensive\r\n" + 
			"wtfgaragesale\r\n" + 
			"Whatthefuckgetitoffme\r\n" + 
			"imsorryjon\r\n" + 
			"mildlyinfuriating\r\n" + 
			"crappydesign\r\n" + 
			"rage\r\n" + 
			"Bad_Cop_No_Donut\r\n" + 
			"gifsthatendtoosoon\r\n" + 
			"peoplebeingjerks\r\n" + 
			"casualchildabuse\r\n" + 
			"fuckthesepeople\r\n" + 
			"makemesuffer\r\n" + 
			"cursedimages\r\n" + 
			"cursedcomments\r\n" + 
			"tihi\r\n" + 
			"blursedimages\r\n" + 
			"cursed_images\r\n" + 
			"blessedimages\r\n" + 
			"imgoingtohellforthis\r\n" + 
			"toosoon\r\n" + 
			"trashy\r\n" + 
			"awfuleyebrows\r\n" + 
			"awfuleverything\r\n" + 
			"13or30\r\n" + 
			"ghettoglamourshots\r\n" + 
			"peopleofwalmart\r\n" + 
			"hittablefaces\r\n" + 
			"punchablefaces\r\n" + 
			"botchedsurgeries\r\n" + 
			"subwaycreatures\r\n" + 
			"nosleep\r\n" + 
			"morbidreality\r\n" + 
			"whatcouldgowrong\r\n" + 
			"Glitch_in_the_Matrix\r\n" + 
			"Paranormal\r\n" + 
			"nononono\r\n" + 
			"horror\r\n" + 
			"shortscarystories\r\n" + 
			"lastimages\r\n" + 
			"peoplefuckingdying\r\n" + 
			"serialkillers\r\n" + 
			"WhyWereTheyFilming\r\n" + 
			"WinStupidPrizes\r\n" + 
			"scarysigns\r\n" + 
			"ghosts\r\n" + 
			"crimescene\r\n" + 
			"creepy\r\n" + 
			"creepypasta\r\n" + 
			"creepysigns\r\n" + 
			"megalophobia\r\n" + 
			"ImaginaryMonsters\r\n" + 
			"ImaginaryLeviathans\r\n" + 
			"ImaginaryMindscapes\r\n" + 
			"imaginarycharacters\r\n" + 
			"imaginarylandscapes\r\n" + 
			"imaginarymaps\r\n" + 
			"SympatheticMonsters\r\n" + 
			"imaginarywesteros\r\n" + 
			"imaginarysliceoflife\r\n" + 
			"thalassophobia\r\n" + 
			"TheDepthsBelow\r\n" + 
			"submechanophobia\r\n" + 
			"freebies\r\n" + 
			"fullmoviesonyoutube\r\n" + 
			"efreebies\r\n" + 
			"randomactsofgaming\r\n" + 
			"freeEbooks\r\n" + 
			"fullmoviesonvimeo\r\n" + 
			"freegamesonsteam\r\n" + 
			"googleplaydeals\r\n" + 
			"megalinks\r\n" + 
			"opendirectories\r\n" + 
			"Random_Acts_Of_Pizza\r\n" + 
			"coupons\r\n" + 
			"dealsreddit\r\n" + 
			"freegamefindings\r\n" + 
			"deals\r\n" + 
			"assistance\r\n" + 
			"free\r\n" + 
			"MaleFashionAdvice\r\n" + 
			"everymanshouldknow\r\n" + 
			"askmen\r\n" + 
			"frugalmalefashion\r\n" + 
			"MensRights\r\n" + 
			"malelifestyle\r\n" + 
			"trollychromosome\r\n" + 
			"malelivingspace\r\n" + 
			"malehairadvice\r\n" + 
			"malefashion\r\n" + 
			"bigdickproblems\r\n" + 
			"mgtow\r\n" + 
			"askmenover30\r\n" + 
			"TwoXChromosomes\r\n" + 
			"askwomen\r\n" + 
			"LadyBoners\r\n" + 
			"TrollXChromosomes\r\n" + 
			"femalefashionadvice\r\n" + 
			"xxfitness\r\n" + 
			"TheGirlSurvivalGuide\r\n" + 
			"abrathatfits\r\n" + 
			"badwomensanatomy\r\n" + 
			"nothowgirlswork\r\n" + 
			"menwritingwomen\r\n" + 
			"MapPorn\r\n" + 
			"polandball\r\n" + 
			"vexillology\r\n" + 
			"SouthAfrica\r\n" + 
			"europe\r\n" + 
			"ireland\r\n" + 
			"thenetherlands\r\n" + 
			"denmark\r\n" + 
			"italy\r\n" + 
			"norge\r\n" + 
			"polska\r\n" + 
			"suomi\r\n" + 
			"romania\r\n" + 
			"belgium\r\n" + 
			"scotland\r\n" + 
			"austria\r\n" + 
			"france\r\n" + 
			"french\r\n" + 
			"de\r\n" + 
			"germany\r\n" + 
			"german\r\n" + 
			"ANormalDayInRussia\r\n" + 
			"youseecomrade\r\n" + 
			"gtaorrussia\r\n" + 
			"sweden\r\n" + 
			"SWARJE\r\n" + 
			"swedishproblems\r\n" + 
			"intresseklubben\r\n" + 
			"svenskpolitik\r\n" + 
			"spop\r\n" + 
			"Allsvenskan\r\n" + 
			"unitedkingdom\r\n" + 
			"britishproblems\r\n" + 
			"london\r\n" + 
			"ukpolitics\r\n" + 
			"casualuk\r\n" + 
			"canada\r\n" + 
			"toronto\r\n" + 
			"vancouver\r\n" + 
			"canadapolitics\r\n" + 
			"calgary\r\n" + 
			"personalfinancecanada\r\n" + 
			"mexico\r\n" + 
			"MURICA\r\n" + 
			"nyc\r\n" + 
			"chicago\r\n" + 
			"portland\r\n" + 
			"boston\r\n" + 
			"atlanta\r\n" + 
			"washingtondc\r\n" + 
			"philadelphia\r\n" + 
			"newjersey\r\n" + 
			"minnesota\r\n" + 
			"michigan\r\n" + 
			"losangeles\r\n" + 
			"sanfrancisco\r\n" + 
			"bayarea\r\n" + 
			"california\r\n" + 
			"sandiego\r\n" + 
			"disneyland\r\n" + 
			"denver\r\n" + 
			"colorado\r\n" + 
			"floridaman\r\n" + 
			"waltdisneyworld\r\n" + 
			"austin\r\n" + 
			"houston\r\n" + 
			"texas\r\n" + 
			"dallas\r\n" + 
			"seattle\r\n" + 
			"SeattleWA\r\n" + 
			"australia\r\n" + 
			"newzealand\r\n" + 
			"melbourne\r\n" + 
			"sydney\r\n" + 
			"Philippines\r\n" + 
			"india\r\n" + 
			"singapore\r\n" + 
			"china\r\n" + 
			"hongkong\r\n" + 
			"japan\r\n" + 
			"japanpics\r\n" + 
			"japantravel\r\n" + 
			"kpop\r\n" + 
			"pyongyang\r\n" + 
			"korea\r\n" + 
			"brasil\r\n" + 
			"argentina\r\n" + 
			"OutOfTheLoop\r\n" + 
			"nocontext\r\n" + 
			"tldr\r\n" + 
			"Enhancement\r\n" + 
			"SecretSanta\r\n" + 
			"MuseumOfReddit\r\n" + 
			"theoryofreddit\r\n" + 
			"threadkillers\r\n" + 
			"evenwithcontext\r\n" + 
			"beetlejuicing\r\n" + 
			"redditinreddit\r\n" + 
			"announcements\r\n" + 
			"blog\r\n" + 
			"beta\r\n" + 
			"place\r\n" + 
			"sequence\r\n" + 
			"thebutton\r\n" + 
			"circleoftrust\r\n" + 
			"baconreader\r\n" + 
			"alienblue\r\n" + 
			"baconit\r\n" + 
			"redditsync\r\n" + 
			"relayforreddit\r\n" + 
			"apolloapp\r\n" + 
			"redditmobile\r\n" + 
			"Circlejerk\r\n" + 
			"DiWHY\r\n" + 
			"frugal_jerk\r\n" + 
			"moviescirclejerk\r\n" + 
			"SubredditDrama\r\n" + 
			"drama\r\n" + 
			"hobbydrama\r\n" + 
			"rbi\r\n" + 
			"ShitRedditSays\r\n" + 
			"karmaconspiracy\r\n" + 
			"undelete\r\n" + 
			"jesuschristreddit\r\n" + 
			"karmacourt\r\n" + 
			"titlegore\r\n" + 
			"ShitAmericansSay\r\n" + 
			"againsthatesubreddits\r\n" + 
			"bestof\r\n" + 
			"DepthHub\r\n" + 
			"BestOfReports\r\n" + 
			"bestoflegaladvice\r\n" + 
			"punpatrol\r\n" + 
			"redditsings\r\n" + 
			"subredditoftheday\r\n" + 
			"wowthissubexists\r\n" + 
			"newreddits\r\n" + 
			"ofcoursethatsathing\r\n" + 
			"findareddit\r\n" + 
			"modnews\r\n" + 
			"redditrequest\r\n" + 
			"subredditsimulator\r\n" + 
			"subredditsimmeta\r\n" + 
			"TrueReddit\r\n" + 
			"awesome\r\n" + 
			"TipOfMyTongue\r\n" + 
			"TipOfMyPenis\r\n" + 
			"woahdude\r\n" + 
			"frisson\r\n" + 
			"asmr\r\n" + 
			"VaporwaveAesthetics\r\n" + 
			"glitchinthematrix\r\n" + 
			"earthporn\r\n" + 
			"hardcoreaww\r\n" + 
			"hitmanimals\r\n" + 
			"natureisfuckinglit\r\n" + 
			"heavyseas\r\n" + 
			"marijuanaenthusiasts\r\n" + 
			"succulents\r\n" + 
			"mycology\r\n" + 
			"bonsai\r\n" + 
			"TreesSuckingOnThings\r\n" + 
			"houseplants\r\n" + 
			"natureismetal\r\n" + 
			"Natureisbrutal\r\n" + 
			"naturewasmetal\r\n" + 
			"weathergifs\r\n" + 
			"tropicalweather\r\n" + 
			"worldnews\r\n" + 
			"news\r\n" + 
			"nottheonion\r\n" + 
			"UpliftingNews\r\n" + 
			"offbeat\r\n" + 
			"gamernews\r\n" + 
			"floridaman\r\n" + 
			"energy\r\n" + 
			"syriancivilwar\r\n" + 
			"truecrime\r\n" + 
			"TheOnion\r\n" + 
			"AteTheOnion\r\n" + 
			"OldSchoolCool\r\n" + 
			"TheWayWeWere\r\n" + 
			"nostalgia\r\n" + 
			"vinyl\r\n" + 
			"forwardsfromgrandma\r\n" + 
			"oldphotosinreallife\r\n" + 
			"firstworldanarchists\r\n" + 
			"wheredidthesodago\r\n" + 
			"unexpectedthuglife\r\n" + 
			"youdontsurf\r\n" + 
			"montageparodies\r\n" + 
			"outside\r\n" + 
			"OSHA\r\n" + 
			"hailcorporate\r\n" + 
			"im14andthisisdeep\r\n" + 
			"bollywoodrealism\r\n" + 
			"AccidentalRenaissance\r\n" + 
			"maliciouscompliance\r\n" + 
			"fakehistoryporn\r\n" + 
			"coaxedintoasnafu\r\n" + 
			"irleastereggs\r\n" + 
			"EarthPorn\r\n" + 
			"HistoryPorn\r\n" + 
			"FoodPorn\r\n" + 
			"JusticePorn\r\n" + 
			"AbandonedPorn\r\n" + 
			"SpacePorn\r\n" + 
			"RoomPorn\r\n" + 
			"QuotesPorn\r\n" + 
			"MapPorn\r\n" + 
			"CityPorn\r\n" + 
			"carporn\r\n" + 
			"humanporn\r\n" + 
			"penmanshipporn\r\n" + 
			"militaryporn\r\n" + 
			"DesignPorn\r\n" + 
			"ThingsCutInHalfPorn\r\n" + 
			"ArchitecturePorn\r\n" + 
			"ExposurePorn\r\n" + 
			"futureporn\r\n" + 
			"adrenalineporn\r\n" + 
			"waterporn\r\n" + 
			"machineporn\r\n" + 
			"animalporn\r\n" + 
			"movieposterporn\r\n" + 
			"illusionporn\r\n" + 
			"destructionporn\r\n" + 
			"adporn\r\n" + 
			"artefactporn\r\n" + 
			"gunporn\r\n" + 
			"skyporn\r\n" + 
			"powerwashingporn\r\n" + 
			"ArtPorn\r\n" + 
			"InfrastructurePorn\r\n" + 
			"VillagePorn\r\n" + 
			"shockwaveporn\r\n" + 
			"productporn\r\n" + 
			"macroporn\r\n" + 
			"cabinporn\r\n" + 
			"houseporn\r\n" + 
			"mineralporn\r\n" + 
			"microporn\r\n" + 
			"shittyaskscience\r\n" + 
			"shittyfoodporn\r\n" + 
			"shittyreactiongifs\r\n" + 
			"crappydesign\r\n" + 
			"Shitty_Car_Mods\r\n" + 
			"shittyadvice\r\n" + 
			"shittyrobots\r\n" + 
			"ShittyLifeProTips\r\n" + 
			"shittykickstarters\r\n" + 
			"shittyanimalfacts\r\n" + 
			"shitpost\r\n" + 
			"shittymoviedetails\r\n" + 
			"unexpected\r\n" + 
			"UnexpectedThugLife\r\n" + 
			"misleadingthumbnails\r\n" + 
			"unexpectedjihad\r\n" + 
			"slygifs\r\n" + 
			"blackmagicfuckery\r\n" + 
			"unexpectedhogwarts\r\n" + 
			"UnexpectedMulaney\r\n" + 
			"AbandonedPorn\r\n" + 
			"OddlySatisfying\r\n" + 
			"RoomPorn\r\n" + 
			"nonononoyes\r\n" + 
			"minimalism\r\n" + 
			"CityPorn\r\n" + 
			"penmanshipporn\r\n" + 
			"Cinemagraphs\r\n" + 
			"ImaginaryLandscapes\r\n" + 
			"eyebleach\r\n" + 
			"DesignPorn\r\n" + 
			"perfectloops\r\n" + 
			"perfectfit\r\n" + 
			"humansbeingbros\r\n" + 
			"powerwashingporn\r\n" + 
			"nevertellmetheodds\r\n" + 
			"typography\r\n" + 
			"cozyplaces\r\n" + 
			"breathinginformation\r\n" + 
			"desirepath\r\n" + 
			"tiltshift\r\n" + 
			"mostbeautiful\r\n" + 
			"AmateurRoomPorn\r\n" + 
			"slygifs\r\n" + 
			"raining\r\n" + 
			"AccidentalWesAnderson\r\n" + 
			"unstirredpaint\r\n" + 
			"handwriting\r\n" + 
			"thatpeelingfeeling\r\n" + 
			"gtage\r\n" + 
			"holdmybeer\r\n" + 
			"holdmyjuicebox\r\n" + 
			"holdmyfries\r\n" + 
			"holdmybeaker\r\n" + 
			"holdmycosmo\r\n" + 
			"holdmycatnip\r\n" + 
			"holdmyredbull\r\n" + 
			"holdmyfeedingtube\r\n" + 
			"fiftyfifty\r\n" + 
			"firstworldproblems\r\n" + 
			"idiotsfightingthings\r\n" + 
			"whatsinthisthing\r\n" + 
			"notinteresting\r\n" + 
			"fifthworldpics\r\n" + 
			"drunkorakid\r\n" + 
			"pussypassdenied\r\n" + 
			"UNBGBBIIVCHIDCTIICBG\r\n" + 
			"Justfuckmyshitup\r\n" + 
			"BestOfStreamingVideo\r\n" + 
			"CatastrophicFailure\r\n" + 
			"evilbuildings\r\n" + 
			"urbanhell\r\n" + 
			"justiceserved\r\n" + 
			"mypeopleneedme\r\n" + 
			"notmyjob\r\n" + 
			"onejob\r\n" + 
			"sweatypalms\r\n" + 
			"therewasanattempt\r\n" + 
			"bitchimabus\r\n" + 
			"greendawn\r\n" + 
			"thingsforants\r\n" + 
			"youseeingthisshit\r\n" + 
			"hmmm\r\n" + 
			"hadtohurt\r\n" + 
			"MandelaEffect\r\n" + 
			"mildlypenis\r\n" + 
			"redditdayof\r\n" + 
			"instantkarma\r\n" + 
			"2healthbars\r\n" + 
			"collapse\r\n" + 
			"slavs_squatting\r\n" + 
			"confusing_perspective\r\n" + 
			"the_pack\r\n" + 
			"unpopularopinion\r\n" + 
			"okbuddyretard\r\n" + 
			"nextfuckinglevel\r\n" + 
			"ooer\r\n" + 
			"happycryingdads\r\n" + 
			"FullScorpion\r\n" + 
			"instantregret\r\n" + 
			"MildlyVandalised\r\n" + 
			"watchpeoplesurvive\r\n" + 
			"tendies\r\n" + 
			"dontputyourdickinthat\r\n" + 
			"whatintarnation\r\n" + 
			"tworedditorsonecup\r\n" + 
			"ExpandDong\r\n" + 
			"wackytictacs\r\n" + 
			"halloween\r\n" + 
			"whatcouldgoright\r\n" + 
			"hmmmgifs\r\n" + 
			"bizarrebuildings\r\n" + 
			"inclusiveor\r\n" + 
			"lostgeneration\r\n" + 
			"kurzgesagt\r\n" + 
			"boop\r\n" + 
			"fightporn\r\n" + 
			"tooktoomuch\r\n" + 
			"humansaremetal\r\n" + 
			"theyknew\r\n" + 
			"fbiopenup\r\n" + 
			"fuckyouinparticular\r\n" + 
			"idiotsnearlydying\r\n" + 
			"AAAAAAAAAAAAAAAAA\r\n" + 
			"chaoticgood\r\n" + 
			"prisonwallet\r\n" + 
			"mindcrack\r\n" + 
			"twitchplayspokemon\r\n" + 
			"battlefield3\r\n" + 
			"punchablefaces\r\n" + 
			"csgobetting\r\n" + 
			"historicalwhatif\r\n" + 
			"nsfw\r\n" + 
			"nsfw2\r\n" + 
			"TipOfMyPenis\r\n" + 
			"bonermaterial\r\n" + 
			"nsfw411\r\n" + 
			"iWantToFuckHer\r\n" + 
			"exxxtras\r\n" + 
			"distension\r\n" + 
			"bimbofetish\r\n" + 
			"christiangirls\r\n" + 
			"dirtygaming\r\n" + 
			"sexybutnotporn\r\n" + 
			"femalepov\r\n" + 
			"omgbeckylookathiscock\r\n" + 
			"sexygirls\r\n" + 
			"breedingmaterial\r\n" + 
			"canthold\r\n" + 
			"toocuteforporn\r\n" + 
			"justhotwomen\r\n" + 
			"stripgirls\r\n" + 
			"hotstuffnsfw\r\n" + 
			"uncommonposes\r\n" + 
			"gifsofremoval\r\n" + 
			"nostalgiafapping\r\n" + 
			"truefmk\r\n" + 
			"nudes\r\n" + 
			"milf\r\n" + 
			"gonewild30plus\r\n" + 
			"preggoporn\r\n" + 
			"realmoms\r\n" + 
			"agedbeauty\r\n" + 
			"legalteens\r\n" + 
			"collegesluts\r\n" + 
			"adorableporn\r\n" + 
			"legalteensXXX\r\n" + 
			"gonewild18\r\n" + 
			"18_19\r\n" + 
			"just18\r\n" + 
			"PornStarletHQ\r\n" + 
			"fauxbait\r\n" + 
			"realgirls\r\n" + 
			"amateur\r\n" + 
			"homemadexxx\r\n" + 
			"dirtypenpals\r\n" + 
			"FestivalSluts\r\n" + 
			"CollegeAmateurs\r\n" + 
			"amateurcumsluts\r\n" + 
			"nsfw_amateurs\r\n" + 
			"funwithfriends\r\n" + 
			"randomsexiness\r\n" + 
			"amateurporn\r\n" + 
			"normalnudes\r\n" + 
			"ItsAmateurHour\r\n" + 
			"irlgirls\r\n" + 
			"verifiedamateurs\r\n" + 
			"Camwhores\r\n" + 
			"camsluts\r\n" + 
			"streamersgonewild\r\n" + 
			"GoneWild\r\n" + 
			"PetiteGoneWild\r\n" + 
			"gonewildstories\r\n" + 
			"GoneWildTube\r\n" + 
			"treesgonewild\r\n" + 
			"gonewildaudio\r\n" + 
			"GWNerdy\r\n" + 
			"gonemild\r\n" + 
			"altgonewild\r\n" + 
			"gifsgonewild\r\n" + 
			"analgw\r\n" + 
			"gonewildsmiles\r\n" + 
			"onstageGW\r\n" + 
			"RepressedGoneWild\r\n" + 
			"bdsmgw\r\n" + 
			"UnderwearGW\r\n" + 
			"LabiaGW\r\n" + 
			"TributeMe\r\n" + 
			"WeddingsGoneWild\r\n" + 
			"gwpublic\r\n" + 
			"assholegonewild\r\n" + 
			"leggingsgonewild\r\n" + 
			"dykesgonewild\r\n" + 
			"goneerotic\r\n" + 
			"snapchatgw\r\n" + 
			"gonewildhairy\r\n" + 
			"gonewildtrans\r\n" + 
			"gonwild\r\n" + 
			"ratemynudebody\r\n" + 
			"gonewild30plus\r\n" + 
			"gonewild18\r\n" + 
			"onmww\r\n" + 
			"GWCouples\r\n" + 
			"gonewildcouples\r\n" + 
			"gwcumsluts\r\n" + 
			"WouldYouFuckMyWife\r\n" + 
			"couplesgonewild\r\n" + 
			"gonewildcurvy\r\n" + 
			"GoneWildplus\r\n" + 
			"BigBoobsGW\r\n" + 
			"bigboobsgonewild\r\n" + 
			"mycleavage\r\n" + 
			"gonewildchubby\r\n" + 
			"AsiansGoneWild\r\n" + 
			"gonewildcolor\r\n" + 
			"indiansgonewild\r\n" + 
			"latinasgw\r\n" + 
			"pawgtastic\r\n" + 
			"workgonewild\r\n" + 
			"GoneWildScrubs\r\n" + 
			"swingersgw\r\n" + 
			"militarygonewild\r\n" + 
			"NSFW_Snapchat\r\n" + 
			"snapchat_sluts\r\n" + 
			"snapleaks\r\n" + 
			"wifesharing\r\n" + 
			"hotwife\r\n" + 
			"wouldyoufuckmywife\r\n" + 
			"slutwife\r\n" + 
			"rule34\r\n" + 
			"ecchi\r\n" + 
			"futanari\r\n" + 
			"doujinshi\r\n" + 
			"yiff\r\n" + 
			"furry\r\n" + 
			"monstergirl\r\n" + 
			"rule34_comics\r\n" + 
			"sex_comics\r\n" + 
			"hentai\r\n" + 
			"hentai_gif\r\n" + 
			"WesternHentai\r\n" + 
			"hentai_irl\r\n" + 
			"overwatch_porn\r\n" + 
			"pokeporn\r\n" + 
			"bowsette\r\n" + 
			"rule34lol\r\n" + 
			"rule34overwatch\r\n" + 
			"BDSM\r\n" + 
			"Bondage\r\n" + 
			"BDSMcommunity\r\n" + 
			"bdsmgw\r\n" + 
			"femdom\r\n" + 
			"blowjobs\r\n" + 
			"lipsthatgrip\r\n" + 
			"deepthroat\r\n" + 
			"onherknees\r\n" + 
			"blowjobsandwich\r\n" + 
			"iwanttosuckcock\r\n" + 
			"ass\r\n" + 
			"asstastic\r\n" + 
			"facedownassup\r\n" + 
			"assinthong\r\n" + 
			"bigasses\r\n" + 
			"buttplug\r\n" + 
			"TheUnderbun\r\n" + 
			"booty\r\n" + 
			"pawg\r\n" + 
			"paag\r\n" + 
			"cutelittlebutts\r\n" + 
			"hipcleavage\r\n" + 
			"frogbutt\r\n" + 
			"HungryButts\r\n" + 
			"cottontails\r\n" + 
			"lovetowatchyouleave\r\n" + 
			"celebritybutts\r\n" + 
			"cosplaybutts\r\n" + 
			"whooties\r\n" + 
			"anal\r\n" + 
			"analgw\r\n" + 
			"painal\r\n" + 
			"masterofanal\r\n" + 
			"buttsharpies\r\n" + 
			"asshole\r\n" + 
			"AssholeBehindThong\r\n" + 
			"assholegonewild\r\n" + 
			"spreadem\r\n" + 
			"girlsinyogapants\r\n" + 
			"yogapants\r\n" + 
			"boobies\r\n" + 
			"TittyDrop\r\n" + 
			"boltedontits\r\n" + 
			"boobbounce\r\n" + 
			"boobs\r\n" + 
			"downblouse\r\n" + 
			"homegrowntits\r\n" + 
			"cleavage\r\n" + 
			"breastenvy\r\n" + 
			"youtubetitties\r\n" + 
			"torpedotits\r\n" + 
			"thehangingboobs\r\n" + 
			"page3glamour\r\n" + 
			"fortyfivefiftyfive\r\n" + 
			"tits\r\n" + 
			"amazingtits\r\n" + 
			"BustyPetite\r\n" + 
			"hugeboobs\r\n" + 
			"stacked\r\n" + 
			"burstingout\r\n" + 
			"BigBoobsGW\r\n" + 
			"bigboobsgonewild\r\n" + 
			"2busty2hide\r\n" + 
			"bigtiddygothgf\r\n" + 
			"engorgedveinybreasts\r\n" + 
			"bigtitsinbikinis\r\n" + 
			"pokies\r\n" + 
			"ghostnipples\r\n" + 
			"nipples\r\n" + 
			"puffies\r\n" + 
			"lactation\r\n" + 
			"tinytits\r\n" + 
			"aa_cups\r\n" + 
			"titfuck\r\n" + 
			"clothedtitfuck\r\n" + 
			"braceface\r\n" + 
			"GirlswithNeonHair\r\n" + 
			"shorthairchicks\r\n" + 
			"blonde\r\n" + 
			"girlsinyogapants\r\n" + 
			"stockings\r\n" + 
			"legs\r\n" + 
			"tightshorts\r\n" + 
			"buttsandbarefeet\r\n" + 
			"feet\r\n" + 
			"datgap\r\n" + 
			"thighhighs\r\n" + 
			"thickthighs\r\n" + 
			"thighdeology\r\n" + 
			"pussy\r\n" + 
			"rearpussy\r\n" + 
			"innie\r\n" + 
			"simps\r\n" + 
			"pelfie\r\n" + 
			"LabiaGW\r\n" + 
			"godpussy\r\n" + 
			"presenting\r\n" + 
			"cameltoe\r\n" + 
			"hairypussy\r\n" + 
			"pantiestotheside\r\n" + 
			"breakingtheseal\r\n" + 
			"moundofvenus\r\n" + 
			"pussymound\r\n" + 
			"Hotchickswithtattoos\r\n" + 
			"sexyfrex\r\n" + 
			"tanlines\r\n" + 
			"oilporn\r\n" + 
			"ComplexionExcellence\r\n" + 
			"SexyTummies\r\n" + 
			"theratio\r\n" + 
			"bodyperfection\r\n" + 
			"samespecies\r\n" + 
			"athleticgirls\r\n" + 
			"coltish\r\n" + 
			"gonewildcurvy\r\n" + 
			"curvy\r\n" + 
			"gonewildplus\r\n" + 
			"thick\r\n" + 
			"juicyasians\r\n" + 
			"voluptuous\r\n" + 
			"biggerthanyouthought\r\n" + 
			"jigglefuck\r\n" + 
			"chubby\r\n" + 
			"SlimThick\r\n" + 
			"massivetitsnass\r\n" + 
			"thicker\r\n" + 
			"thickthighs\r\n" + 
			"tightsqueeze\r\n" + 
			"casualjiggles\r\n" + 
			"bbw\r\n" + 
			"gonewildchubby\r\n" + 
			"fitgirls\r\n" + 
			"fitnakedgirls\r\n" + 
			"BustyPetite\r\n" + 
			"dirtysmall\r\n" + 
			"petitegonewild\r\n" + 
			"funsized\r\n" + 
			"hugedicktinychick\r\n" + 
			"petite\r\n" + 
			"skinnytail\r\n" + 
			"volleyballgirls\r\n" + 
			"Ohlympics\r\n" + 
			"celebnsfw\r\n" + 
			"WatchItForThePlot\r\n" + 
			"nsfwcelebarchive\r\n" + 
			"oldschoolcoolNSFW\r\n" + 
			"extramile\r\n" + 
			"jerkofftocelebs\r\n" + 
			"celebritybutts\r\n" + 
			"onoffcelebs\r\n" + 
			"celebswithbigtits\r\n" + 
			"youtubersgonewild\r\n" + 
			"cumsluts\r\n" + 
			"GirlsFinishingTheJob\r\n" + 
			"cumfetish\r\n" + 
			"amateurcumsluts\r\n" + 
			"cumcoveredfucking\r\n" + 
			"cumhaters\r\n" + 
			"thickloads\r\n" + 
			"before_after_cumsluts\r\n" + 
			"pulsatingcumshots\r\n" + 
			"impressedbycum\r\n" + 
			"creampies\r\n" + 
			"throatpies\r\n" + 
			"FacialFun\r\n" + 
			"cumonclothes\r\n" + 
			"oralcreampie\r\n" + 
			"creampie\r\n" + 
			"HappyEmbarrassedGirls\r\n" + 
			"unashamed\r\n" + 
			"borednignored\r\n" + 
			"annoyedtobenude\r\n" + 
			"damngoodinterracial\r\n" + 
			"AsianHotties\r\n" + 
			"AsiansGoneWild\r\n" + 
			"realasians\r\n" + 
			"juicyasians\r\n" + 
			"AsianNSFW\r\n" + 
			"nextdoorasians\r\n" + 
			"asianporn\r\n" + 
			"bustyasians\r\n" + 
			"paag\r\n" + 
			"IndianBabes\r\n" + 
			"indiansgonewild\r\n" + 
			"NSFW_Japan\r\n" + 
			"javdownloadcenter\r\n" + 
			"kpopfap\r\n" + 
			"NSFW_Korea\r\n" + 
			"WomenOfColor\r\n" + 
			"darkangels\r\n" + 
			"blackchickswhitedicks\r\n" + 
			"ebony\r\n" + 
			"Afrodisiac\r\n" + 
			"ginger\r\n" + 
			"redheads\r\n" + 
			"latinas\r\n" + 
			"latinasgw\r\n" + 
			"latinacuties\r\n" + 
			"palegirls\r\n" + 
			"pawg\r\n" + 
			"snowwhites\r\n" + 
			"whooties\r\n" + 
			"NSFW_GIF\r\n" + 
			"nsfw_gifs\r\n" + 
			"porn_gifs\r\n" + 
			"porninfifteenseconds\r\n" + 
			"CuteModeSlutMode\r\n" + 
			"60fpsporn\r\n" + 
			"NSFW_HTML5\r\n" + 
			"the_best_nsfw_gifs\r\n" + 
			"verticalgifs\r\n" + 
			"besthqporngifs\r\n" + 
			"twingirls\r\n" + 
			"groupofnudegirls\r\n" + 
			"Ifyouhadtopickone\r\n" + 
			"nsfwhardcore\r\n" + 
			"SheLikesItRough\r\n" + 
			"strugglefucking\r\n" + 
			"jigglefuck\r\n" + 
			"whenitgoesin\r\n" + 
			"outercourse\r\n" + 
			"gangbang\r\n" + 
			"pegging\r\n" + 
			"insertions\r\n" + 
			"passionx\r\n" + 
			"xsome\r\n" + 
			"cuckold\r\n" + 
			"cuckquean\r\n" + 
			"breeding\r\n" + 
			"forcedcreampie\r\n" + 
			"hugedicktinychick\r\n" + 
			"amateurgirlsbigcocks\r\n" + 
			"facesitting\r\n" + 
			"nsfw_plowcam\r\n" + 
			"pronebone\r\n" + 
			"facefuck\r\n" + 
			"girlswhoride\r\n" + 
			"60fpsporn\r\n" + 
			"highresNSFW\r\n" + 
			"NSFW_HTML5\r\n" + 
			"incestporn\r\n" + 
			"wincest\r\n" + 
			"incest_gifs\r\n" + 
			"remylacroix\r\n" + 
			"Anjelica_Ebbi\r\n" + 
			"BlancNoir\r\n" + 
			"rileyreid\r\n" + 
			"tessafowler\r\n" + 
			"lilyivy\r\n" + 
			"mycherrycrush\r\n" + 
			"gillianbarnes\r\n" + 
			"emilybloom\r\n" + 
			"miamalkova\r\n" + 
			"sashagrey\r\n" + 
			"angelawhite\r\n" + 
			"miakhalifa\r\n" + 
			"alexapearl\r\n" + 
			"missalice_18\r\n" + 
			"lanarhoades\r\n" + 
			"evalovia\r\n" + 
			"GiannaMichaels\r\n" + 
			"erinashford\r\n" + 
			"sextrophies\r\n" + 
			"sabrina_nichole\r\n" + 
			"LiyaSilver\r\n" + 
			"MelissaDebling\r\n" + 
			"AdrianaChechik\r\n" + 
			"sarah_xxx\r\n" + 
			"dollywinks\r\n" + 
			"funsizedasian\r\n" + 
			"Kawaiiikitten\r\n" + 
			"legendarylootz\r\n" + 
			"sexyflowerwater\r\n" + 
			"keriberry_420\r\n" + 
			"justpeachyy\r\n" + 
			"hopelesssofrantic\r\n" + 
			"lesbians\r\n" + 
			"StraightGirlsPlaying\r\n" + 
			"girlskissing\r\n" + 
			"mmgirls\r\n" + 
			"dykesgonewild\r\n" + 
			"holdthemoan\r\n" + 
			"O_faces\r\n" + 
			"jilling\r\n" + 
			"gettingherselfoff\r\n" + 
			"quiver\r\n" + 
			"GirlsHumpingThings\r\n" + 
			"forcedorgasms\r\n" + 
			"mmgirls\r\n" + 
			"ruinedorgasms\r\n" + 
			"realahegao\r\n" + 
			"suctiondildos\r\n" + 
			"baddragon\r\n" + 
			"grool\r\n" + 
			"squirting\r\n" + 
			"ladybonersgw\r\n" + 
			"massivecock\r\n" + 
			"chickflixxx\r\n" + 
			"gaybrosgonewild\r\n" + 
			"sissies\r\n" + 
			"penis\r\n" + 
			"freeuse\r\n" + 
			"fuckdoll\r\n" + 
			"degradingholes\r\n" + 
			"fuckmeat\r\n" + 
			"OnOff\r\n" + 
			"nsfwoutfits\r\n" + 
			"girlswithglasses\r\n" + 
			"collared\r\n" + 
			"seethru\r\n" + 
			"sweatermeat\r\n" + 
			"cfnm\r\n" + 
			"nsfwfashion\r\n" + 
			"leotards\r\n" + 
			"whyevenwearanything\r\n" + 
			"shinyporn\r\n" + 
			"bikinis\r\n" + 
			"bikinibridge\r\n" + 
			"bigtitsinbikinis\r\n" + 
			"nsfwcosplay\r\n" + 
			"nsfwcostumes\r\n" + 
			"girlsinschooluniforms\r\n" + 
			"WtSSTaDaMiT\r\n" + 
			"tightdresses\r\n" + 
			"upskirt\r\n" + 
			"stockings\r\n" + 
			"thighhighs\r\n" + 
			"leggingsgonewild\r\n" + 
			"Bottomless_Vixens\r\n" + 
			"tightshorts\r\n" + 
			"tight_shorts\r\n" + 
			"girlsinyogapants\r\n" + 
			"yogapants\r\n" + 
			"lingerie\r\n" + 
			"pantiestotheside\r\n" + 
			"assinthong\r\n" + 
			"AssholeBehindThong\r\n" + 
			"porn\r\n" + 
			"suicidegirls\r\n" + 
			"GirlsDoPorn\r\n" + 
			"pornstarhq\r\n" + 
			"porninaminute\r\n" + 
			"ChangingRooms\r\n" + 
			"workgonewild\r\n" + 
			"FlashingGirls\r\n" + 
			"publicflashing\r\n" + 
			"sexinfrontofothers\r\n" + 
			"NotSafeForNature\r\n" + 
			"gwpublic\r\n" + 
			"realpublicnudity\r\n" + 
			"socialmediasluts\r\n" + 
			"flashingandflaunting\r\n" + 
			"publicsexporn\r\n" + 
			"nakedadventures\r\n" + 
			"trashyboners\r\n" + 
			"flubtrash\r\n" + 
			"realsexyselfies\r\n" + 
			"nude_selfie\r\n" + 
			"Tgirls\r\n" + 
			"traps\r\n" + 
			"futanari\r\n" + 
			"gonewildtrans\r\n" + 
			"tgifs\r\n" + 
			"shemales\r\n" + 
			"femboys\r\n" + 
			"transporn\r\n" + 
			"pornvids\r\n" + 
			"nsfw_videos\r\n" + 
			"dirtysnapchat\r\n" + 
			"randomactsofblowjob\r\n" + 
			"NSFWFunny\r\n" + 
			"pornhubcomments\r\n" + 
			"confusedboners\r\n" + 
			"dirtykikpals\r\n" + 
			"nsfw_wtf\r\n" + 
			"randomactsofmuffdive\r\n" + 
			"stupidslutsclub\r\n" + 
			"sluttyconfessions\r\n" + 
			"jobuds\r\n" + 
			"drunkdrunkenporn\r\n" + 
			"popping\r\n" + 
			"medicalgore";

}
